### ISSUE TITLE
Power Board BOM

### ISSUE THREAD

**Issue by krystiancharubin** [Printrbot/printrboardg2#1]
Hey, I am looking to make a new Power Board for my printer. Is there a BOM for all the necessary components?

**Comment by drphil3d** [comment]
There’s schematics. If you need a replacement I can sell you one.
-- 

Philip Mally
3D Printing & Rapid Prototyping Services
530-205-3210
pmally@gmail.com

**Comment by krystiancharubin** [comment]
Emailed for details

**Comment by krystiancharubin** [comment]
@drphil3d I would very much like to purchase one.
Please email me at krystiancharubin@gmail.com
